# Homebrew Formula for free-playing-cards-online
# This file will be used by GoReleaser to generate the actual formula

class FreePlayingCardsOnline < Formula
  desc "Free online card games - play and build your own"
  homepage "https://github.com/birddigital/free-playing-cards-online"
  url "https://github.com/birddigital/free-playing-cards-online/archive/refs/tags/v1.0.0.tar.gz"
  sha256 "" # Auto-generated by GoReleaser
  license "MIT"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w"), "./cmd/server"
    bin.install "cards-local" => "cards-local"
  end

  def post_install
    var = etc/"free-playing-cards-online"
    var.mkpath
  end

  test do
    system "#{bin}/cards-local", "--help"
  end
end
